### ISSUE TITLE
out of range

### ISSUE THREAD

**Issue by ch-sander** [raffazizzi/biblhertz-iiif-metadata#1]
I get this

> C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF>addmeta.py -u https://dlib2.biblhertz.it/iiif/3/gothaa707 -i https://dlib.biblhertz.it/iiif/gothaa707/manifest.json -c metadata.csv
Traceback (most recent call last):
  File "C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF\addmeta.py", line 103, in <module>
    addmeta()
  File "C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF\addmeta.py", line 83, in addmeta
    items.append(storeAtLevel(int(level), accumulator))
  File "C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF\addmeta.py", line 82, in storeAtLevel
    return storeAtLevel(lv-1, obj[-1]["items"])
IndexError: list index out of range

**Comment by ch-sander** [comment]
I adjusted the CSV and now get this error

> C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF>addmeta.py -u https://dlib2.biblhertz.it/iiif/3/gothaa707 -i https://dlib.biblhertz.it/iiif/gothaa707/manifest.json -c https://docs.google.com/spreadsheets/d/e/2PACX-1vTfa4Q-66Qa_CdNISFBswzZF4Io3uFOI4nG-05tkac1sru3L69bfUZoJC8Rp3lyfmpdzYIzHWPkFJ2B/pubhtml?gid=811546954  & single=true
Traceback (most recent call last):
  File "C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF\addmeta.py", line 103, in <module>
    addmeta()
  File "C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF\addmeta.py", line 57, in addmeta
    canvas = metadata[1]
IndexError: list index out of range
Der Befehl "single" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**Comment by ch-sander** [comment]
problem was solves after first CSV item received level 0 (instead of 1)
