### ISSUE TITLE
csv from url

### ISSUE THREAD

**Issue by ch-sander** [raffazizzi/biblhertz-iiif-metadata#2]
won't load https://docs.google.com/spreadsheets/d/e/2PACX-1vTfa4Q-66Qa_CdNISFBswzZF4Io3uFOI4nG-05tkac1sru3L69bfUZoJC8Rp3lyfmpdzYIzHWPkFJ2B/pubhtml?gid=811546954&single=true

> C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF>addmeta.py -u https://dlib2.biblhertz.it/iiif/3/gothaa707 -i https://dlib.biblhertz.it/iiif/gothaa707/manifest.json -c https://docs.google.com/spreadsheets/d/e/2PACX-1vTfa4Q-66Qa_CdNISFBswzZF4Io3uFOI4nG-05tkac1sru3L69bfUZoJC8Rp3lyfmpdzYIzHWPkFJ2B/pubhtml?gid=811546954  & single=true
Traceback (most recent call last):
  File "C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF\addmeta.py", line 103, in <module>
    addmeta()
  File "C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF\addmeta.py", line 57, in addmeta
    canvas = metadata[1]
IndexError: list index out of range
Der Befehl "single" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

I think cmd cannot handle the link

**Comment by ch-sander** [comment]
similar error if put in ""

> C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF>addmeta.py -u https://dlib2.biblhertz.it/iiif/3/gothaa707 -i https://dlib.biblhertz.it/iiif/gothaa707/manifest.json -c "https://docs.google.com/spreadsheets/d/e/2PACX-1vTfa4Q-66Qa_CdNISFBswzZF4Io3uFOI4nG-05tkac1sru3L69bfUZoJC8Rp3lyfmpdzYIzHWPkFJ2B/pubhtml?gid=811546954&single=true"
Traceback (most recent call last):
  File "C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF\addmeta.py", line 103, in <module>
    addmeta()
  File "C:\Users\Sander\Documents\MEGA\Programme\python\Vigilante_CSV2IIIF\addmeta.py", line 57, in addmeta
    canvas = metadata[1]
IndexError: list index out of range

Maybe the GoogleAPI creates the issue

**Comment by ch-sander** [comment]
my fault, had to use https://docs.google.com/spreadsheets/d/e/2PACX-1vTfa4Q-66Qa_CdNISFBswzZF4Io3uFOI4nG-05tkac1sru3L69bfUZoJC8Rp3lyfmpdzYIzHWPkFJ2B/pub?gid=811546954&single=true&output=csv
