### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ch-sander** [raffazizzi/biblhertz-iiif-metadata#3]
what's going wrong here?

```
C:\Users\Sander>python C:\Users\Sander\Documents\GitHub\biblhertz-iiif-metadata\addmeta.py -u https://dlib2.biblhertz.it/iiif/2/buhmmontpellierh169 -i https://raw.githubusercontent.com/ch-sander/raramagnetica/main/iiif/porta.json -c "https://docs.google.com/spreadsheets/d/e/2PACX-1vTfa4Q-66Qa_CdNISFBswzZF4Io3uFOI4nG-05tkac1sru3L69bfUZoJC8Rp3lyfmpdzYIzHWPkFJ2B/pub?gid=864451923&single=true&output=csv" -o C:\Users\Sander\Documents\GitHub\raramagnetica\iiif\porta.json
Traceback (most recent call last):
  File "C:\Users\Sander\Documents\GitHub\biblhertz-iiif-metadata\addmeta.py", line 104, in <module>
    addmeta()
  File "C:\Users\Sander\Documents\GitHub\biblhertz-iiif-metadata\addmeta.py", line 87, in addmeta
    for item in manifest["items"]:
KeyError: 'items'
```

``` json
"canvases": [
        {
          "@id": "https://dlib2.biblhertz.it/iiif/2/buhmmontpellierh169@0001-canvas",
          "@type": "sc:Canvas",
          "label": "0001",
          "width": 1754,
          "height": 2480,
          "images": [
            {
              "@type": "oa:Annotation",
              "motivation": "sc:painting",
              "@id": "https://dlib2.biblhertz.it/iiif/2/buhmmontpellierh169@0001-ocr",
              "resource": {
                "@id": "https://dlib2.biblhertz.it/iiif/2/buhmmontpellierh169@0001.jp2/full/full/0/default.jpg",
                "@type": "dctypes:Image",
                "format": "image/jpg",
                "width": 1754,
                "height": 2480,
                "service": {
                  "@context": "http://iiif.io/api/image/2/context.json",
                  "@id": "https://dlib2.biblhertz.it/iiif/2/buhmmontpellierh169@0001.jp2",
                  "profile": "http://iiif.io/api/image/2/level2.json"
                }
              },
              "on": "https://dlib2.biblhertz.it/iiif/2/buhmmontpellierh169@0001-canvas"
            }
          ]
        },
```

**Comment by ch-sander** [comment]
solved it myself!
